env:
  global:
    - CC_TEST_REPORTER_ID=e2b176de532d3d4ae08889931aa9679fe2e5e1fdc6eeb9381f93c329068235d5
language: ruby
sudo: false
before_install:
  - |
    if ruby -e "exit(RUBY_ENGINE == 'ruby' && RUBY_VERSION.start_with?('2.2'))"; then
      gem install bundler -v '< 2'
    else
      gem install bundler
    fi
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle list
  # Unit test
  - bundle exec rake
  # Release test
  - bundle exec thor :build
  - ls -l pkg/rack-test-*.gem
  - gem install pkg/rack-test-*.gem
  - gem list rack-test
  - ruby -e 'require "rack/test"'
  - gem specification pkg/rack-test-*.gem --ruby
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - jruby-9.1.13.0
  - jruby-head
gemfile:
  - Gemfile
  - Gemfile.rack-1.x
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
