language: ruby
sudo: false
before_install:
  - which bundle || gem install bundler
script:
  - bundle list
  # Unit test
  - bundle exec rake
  # Release test
  - bundle exec thor :build
  - ls -l pkg/rack-test-*.gem
  - gem install pkg/rack-test-*.gem
  - gem list rack-test
  - ruby -e 'require "rack/test"'
  - gem specification pkg/rack-test-*.gem --ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - jruby-9.1.13.0
  - jruby-head
gemfile:
  - Gemfile
  - Gemfile.rack-1.x
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
